#ifndef APP_SERIAL_ERROR_T_H
#define APP_SERIAL_ERROR_T_H

typedef enum {
	APP_SERIAL_ERROR_UNKNOWN,
	APP_SERIAL_ERROR_NONE,
	APP_SERIAL_ERROR_NO_DATA,
	APP_SERIAL_ERROR_INVALID_DATA,
	APP_SERIAL_ERROR_DEVICE_DISCONNECTED
} appSerialError_t;

#endif
