[env:megaatmega2560]
platform = atmelavr
framework = arduino
board = megaatmega2560
monitor_speed = 115200
upload_port = auto
upload_speed = 115200
build_flags = 
    -D ARDUINO_MEGA=1
    -D BOARD_ATmega2560
test_ignore = test_native

[env:nanoatmega328]
platform = atmelavr
framework = arduino
board = nanoatmega328
monitor_speed = 115200
upload_port = auto
upload_speed = 115200
build_flags = 
    -D ARDUINO_NANO=1
    -D BOARD_ATmega328
test_ignore = test_native

[env:native]
platform = native
build_type = test
build_flags = -I test/native -D NATIVE
test_ignore = test_embedded
lib_deps = fabiobatsilva/ArduinoFake @ ^0.4.0
