#ifndef BUFFER_BLOCK_MODE_H
#define BUFFER_BLOCK_MODE_H

typedef enum  {
	BUFFER_BLOCK_MODE_UNKNOWN,
	BUFFER_BLOCK_MODE_FREE,
	BUFFER_BLOCK_MODE_WRITE,
	BUFFER_BLOCK_MODE_READ,
	BUFFER_BLOCK_MODE_EXPIRED
} bufferBlockMode_t;

#endif
