#ifndef CONNECTION_H
#define CONNECTION_H

#define CONNECTION_UART_BAUD_RATE				38400
#define CONNECTION_UART_DPS						SERIAL_8N1
#define CONNECTION_PACKAGE_DELIMITER_START		'<'
#define CONNECTION_PACKAGE_DELIMITER_STOP		'>'
#define CONNECTION_ERROR_MASK_1					0x40
#define CONNECTION_ERROR_MASK_0					0xBF

#endif
