#ifndef RAZMER2M1104_H
#define RAZMER2M1104_H

#define RAZMER2M_ROWS_COUNT				4
#define RAZMER2M_COLUMNS_COUNT			7
#define RAZMER2M_SIGNS_COUNT			(RAZMER2M_ROWS_COUNT * RAZMER2M_COLUMNS_COUNT)
#define RAZMER2M_CODE_PLUS				0
#define RAZMER2M_CODE_MINUS				9

#endif
